[2025-06-14T09:54:42.707+0000] {scheduler_job_runner.py:843} ERROR - Executor reports task instance <TaskInstance: lp_yolov8_pipeline.run_dvc_pull scheduled__2025-06-14T09:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
